.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after


build:
  extends: .nix
  stage: build
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - eval "$(ssh-agent -s)"
    - ssh-add - <<< "$SSH_PRIVATE_KEY"
    - nix build .\#docker
    - cp result image.tar.gz
  artifacts:
    when: always
    paths:
      - image.tar.gz
