[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cc3dslib"
version = "0.2.0"
description = "A library for CC3D steppables"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "h5py",
]
