[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cc3dslib"
version = "0.0.1"
description = "A library for CC3D steppables"
readme = "README.md"
requires-python = ">=3.10"
